# Generated by Django 4.2 on 2023-07-13 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_tag_delete_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='post',
        ),
        migrations.AddField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='post.post'),
        ),
    ]
