# Generated by Django 4.2 on 2023-07-13 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_tag_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='view',
            field=models.BigIntegerField(default=0),
        ),
    ]
