# Generated by Django 4.2 on 2023-07-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_post_view'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-created', '-view', '-updated')},
        ),
        migrations.AlterField(
            model_name='post',
            name='view',
            field=models.IntegerField(default=0),
        ),
    ]
