# Generated by Django 4.2 on 2023-07-14 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_alter_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='post',
            field=models.ManyToManyField(blank=True, related_name='tags', to='post.post'),
        ),
    ]
